#!/bin/bash

AMI_ID="ami-09c813fb71547fc4f"
SG_ID="sg-00fa736b2eba8959d"

for instance in $@

do
    INSTANCE_ID=$(aws ec2 run-instances --image-id $AMI_ID --instance-type t3.micro --security-group-ids $SG_ID --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$instance}]")

    #Print IP's
    if [ $instance -ne frontend ]; then
        IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[*].Instances[*].[PrivateIpAddress]' --output text)
    else
        IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[*].Instances[*].[PublicIpAddress]' --output text)
    fi
done