#!/bin/bash

AMI_ID="ami-09c813fb71547fc4f"
SG_ID="sg-00fa736b2eba8959d"
ZONE_ID="Z05445223EGIS9AWDWK63"
DOMAIN_NAME="prudhvii.fun"

for instance in $@

do
    INSTANCE_ID=$(aws ec2 run-instances --image-id $AMI_ID --instance-type t3.micro --security-group-ids $SG_ID --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$instance}]" --query 'Instances[0].InstanceId' --output text)

    #Print IP's
    if [ $instance != frontend ]; then
        IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
        RECORD_NAME="$instance.$DOMAIN_NAME"
    else
        IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[*].Instances[*].PrivateIpAddress' --output text)
        RECORD_NAME="$DOMAIN_NAME"
    fi

      echo "$instance: $IP"

    aws route53 change-resource-record-sets \
    --hosted-zone-id Z05445223EGIS9AWDWK63 \
    --change-batch '{
        "Changes": [
            {
                "Action": "UPSERT",
                "ResourceRecordSet": {
                    "Name": "'$RECORD_NAME'",
                    "Type": "A",
                    "TTL": 1,
                    "ResourceRecords": [
                        {
                            "Value": "'$IP'"
                        }
                    ]
                }
            }
        ]
    }'

done